@hostname=localhost
@port=4000

POST http://{{hostname}}:{{port}}/api/auth/create-account
Content-Type: application/json

{
  "name": "Emerson",
  "password": "Password",
  "password_confirmation": "Password",
  "email": "correo@correo.com"
}

###

POST http://{{hostname}}:{{port}}/api/auth/confirm-account
Content-Type: application/json

{
  "token": "925390"
}

###

POST http://{{hostname}}:{{port}}/api/auth/login
Content-Type: application/json

{
  "password": "Password",
  "email": "correo@correo.com"
}

###

POST http://{{hostname}}:{{port}}/api/auth/
Content-Type: application/json

{
  "email": "correo@correo.com"
}