@HOSTNAME=localhost
@PORT=4000
@TOKEN=220192
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzNiMTZhZDYzNDc1MjY4MTc5NmJmZiIsImlhdCI6MTcxOTI4NjI3MCwiZXhwIjoxNzM0ODM4MjcwfQ.BLwH3tBjFhVe4bKzQBN6zpbP5_NjqxieJYWDNM1WC_8


POST http://{{HOSTNAME}}:{{PORT}}/api/auth/create-account
Content-Type: application/json

{
  "name": "Emerson",
  "password": "Password",
  "password_confirmation": "Password",
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/confirm-account
Content-Type: application/json

{
  "token": "{{TOKEN}}"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/login
Content-Type: application/json

{
  "password": "Password",
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/request-code
Content-Type: application/json

{
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/validate-token
Content-Type: application/json

{
  "token": "{{TOKEN}}"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/update-password/{{TOKEN}}
Content-Type: application/json

{
  "password": "Password123",
  "password_confirmation": "Password123"
}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/auth/user
Authorization: Bearer {{ACCESS_JWT}}

###

PUT http://{{HOSTNAME}}:{{PORT}}/api/auth/profile
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "name": "emerson",
  "email": "emerson@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/update-password
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "current_password": "pa",
  "password": "pa",
  "password_confirmation": "pa3"
}
