@HOSTNAME=localhost
@PORT=4000
@TOKEN=220192
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmZiOTg0MTJjMWY0ODI4ODZjZmRmYSIsImlhdCI6MTcxODY3OTY0MiwiZXhwIjoxNzM0MjMxNjQyfQ.H-AMp5xSnmm77m5-2dsWvp2Ke-pQZcGf1iM-iOu0NIQ


POST http://{{HOSTNAME}}:{{PORT}}/api/auth/create-account
Content-Type: application/json

{
  "name": "Emerson",
  "password": "Password",
  "password_confirmation": "Password",
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/confirm-account
Content-Type: application/json

{
  "token": {{TOKEN}}
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/login
Content-Type: application/json

{
  "password": "Password",
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/request-code
Content-Type: application/json

{
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "correo@correo.com"
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/validate-token
Content-Type: application/json

{
  "token": {{TOKEN}}
}

###

POST http://{{HOSTNAME}}:{{PORT}}/api/auth/update-password/{{TOKEN}}
Content-Type: application/json

{
  "password": "Password123",
  "password_confirmation": "Password123"
}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/auth/user
Authorization: Bearer {{ACCESS_JWT}}
