@hostname=localhost
@port=4000


POST http://{{hostname}}:{{port}}/api/projects/
Content-Type: application/json

{
  "projectName": "Ecommerce",
  "clientName": "Adidas",
  "description": "Ecommerce con Next y shopify"
}

###

GET http://{{hostname}}:{{port}}/api/projects/

###

GET http://{{hostname}}:{{port}}/api/projects/1

###

PUT http://{{hostname}}:{{port}}/api/projects/1

###

DELETE http://{{hostname}}:{{port}}/api/projects/1
