@HOSTNAME=localhost
@PORT=4000
@PROJECT_ID=6670eb4e24df5c262300daeb
@ACCESS_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmZiOTg0MTJjMWY0ODI4ODZjZmRmYSIsImlhdCI6MTcxODY3OTY0MiwiZXhwIjoxNzM0MjMxNjQyfQ.H-AMp5xSnmm77m5-2dsWvp2Ke-pQZcGf1iM-iOu0NIQ

POST http://{{HOSTNAME}}:{{PORT}}/api/projects/
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "projectName": "POS",
  "clientName": "Anonymous",
  "description": "POS con Vite y TS"
}

###

GET http://{{HOSTNAME}}:{{PORT}}/api/projects/
Authorization: Bearer {{ACCESS_JWT}}


###

GET http://{{HOSTNAME}}:{{PORT}}/api/projects/{{PROJECT_ID}}
Authorization: Bearer {{ACCESS_JWT}}

###

PUT http://{{HOSTNAME}}:{{PORT}}/api/projects/{{PROJECT_ID}}
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "projectName": "To Do Project - UPDATED",
  "clientName": "Anonymous",
  "description": "To do con Vite y TS"
}

###

DELETE http://{{HOSTNAME}}:{{PORT}}/api/projects/{{PROJECT_ID}}
Authorization: Bearer {{ACCESS_JWT}}

