@hostname=localhost
@port=4000
@projectId=665fd09fecd7a7675e7cafd5


POST http://{{hostname}}:{{port}}/api/projects/{{projectId}}/tasks
Content-Type: application/json

{
    "taskName": "Test",
    "description": "Test"
}
