@hostname=localhost
@port=4000


POST http://{{hostname}}:{{port}}/api/projects/1/
Content-Type: application/json

{
    "taskName": "",
    "description": "",
}

###

GET http://{{hostname}}:{{port}}/api/projects/1/

###

GET http://{{hostname}}:{{port}}/api/projects/1/1

###

PUT http://{{hostname}}:{{port}}/api/projects/1/1

###

DELETE http://{{hostname}}:{{port}}/api/projects/1/1
